#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=90
CONFIG=/etc/vlmcsd.ini
LOG=/var/log/vlmcsd.log

start(){
	config_load vlmcsd
	config_get_bool enabled $1 enabled 0
	[ $enabled -eq 0 ] && exit 0

	if [ ! -f "/var/run/vlmcsd.pid" ]; then
		/usr/bin/vlmcsd -i /etc/vlmcsd.ini -p /var/run/vlmcsd.pid -l $LOG
		echo "KMS Server has started."
	else
		echo "KMS Server has already started."
	fi
}

stop(){
	if [ ! -f "/var/run/vlmcsd.pid" ]; then
		echo "KMS Server is not running."
	else
		pid=`cat /var/run/vlmcsd.pid`
		kill $pid
		rm -f /var/run/vlmcsd.pid
		echo "KMS Server has stopped."
	fi
}

restart(){
	stop
	sleep 1
	start
	echo "KMS Server has restarted."
}
